# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

parameters:
    app.profile_picture.upload_dir: "%kernel.project_dir%/public/uploads/profile-pictures"
    app.profile_picture.public_base_path: "/uploads/profile-pictures"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"

    App\EventListener\AuthenticationSuccessListener:
        tags:
            - name: kernel.event_listener
              event: lexik_jwt_authentication.on_authentication_success
              method: onAuthenticationSuccess
