<?php

namespace App\Enum;

enum AuditEventType: string
{
    case MISSION_DECLARED = 'MISSION_DECLARED';
    case MISSION_DECLARED_APPROVED = 'MISSION_DECLARED_APPROVED';
    case MISSION_DECLARED_REJECTED = 'MISSION_DECLARED_REJECTED';

    // Planning generation & deployment
    case PLANNING_GENERATED              = 'PLANNING_GENERATED';
    case PLANNING_UNASSIGNED_HANDLED     = 'PLANNING_UNASSIGNED_HANDLED';
    case PLANNING_DEPLOYED               = 'PLANNING_DEPLOYED';
    case PLANNING_ARCHIVED               = 'PLANNING_ARCHIVED';
    case MISSION_CREATED_FROM_PLANNING   = 'MISSION_CREATED_FROM_PLANNING';
    case MISSION_OPENED_FROM_PLANNING    = 'MISSION_OPENED_FROM_PLANNING';
    case MISSION_ASSIGNED_FROM_PLANNING  = 'MISSION_ASSIGNED_FROM_PLANNING';
}