<?php

namespace App\Enum;

enum PlanningAlertType: string
{
    case SURGEON_ABSENCE        = 'SURGEON_ABSENCE';
    case INSTRUMENTIST_ABSENCE  = 'INSTRUMENTIST_ABSENCE';
    case SURGEON_CONFLICT       = 'SURGEON_CONFLICT';
    case INSTRUMENTIST_CONFLICT = 'INSTRUMENTIST_CONFLICT';
    case REASSIGNMENT_REQUIRED  = 'REASSIGNMENT_REQUIRED';
    case OCCURRENCE_CANCELLED   = 'OCCURRENCE_CANCELLED';
}
